{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Default value. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_ezstring_default_value_{$class_attribute.id}" value="{$class_attribute.data_text1|wash}" size="30" maxlength="60" />
</div>
