{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base=ContentObjectAttribute}
{ezscript_require( array( 'jquery-ui-1.7.2.custom.min.js', 'ui.datepicker-es.js' ) ) }
{run-once}
<script type="text/javascript" src={"javascript/jquery-ui-1.7.2.custom.min.js"|ezdesign()}></script>
<script type="text/javascript" src={"javascript/ui.datepicker-es.js"|ezdesign()}></script>
{/run-once}
{ezcss_require( array( 'jquery-ui-1.7.2.custom.css' ) ) }
{literal}
<script type="text/javascript">
(function ($) {
	$(document).ready( function()
	{
   	    $.datepicker.setDefaults($.extend({showMonthAfterYear: false}, $.datepicker.regional['es']));
		$('#{/literal}ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_date{literal}').datepicker( 
			{onSelect: function(dateText, inst) { 
				var aux = dateText.split( '/' );				
				$("#" + $(inst).attr( 'id' ).replace( 'date', 'day' ) ).val( aux[0] );
				$("#" + $(inst).attr( 'id' ).replace( 'date', 'month' ) ).val( aux[1] );
				$("#" + $(inst).attr( 'id' ).replace( 'date', 'year' ) ).val( aux[2] );
			}}
			
		);
        $("#delete{/literal}{$attribute.contentclassattribute_id}{literal}").click( function() {
            $( "#"+'ezcoa-{/literal}{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}{literal}_date').val('');
            $( "#"+'ezcoa-{/literal}{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}{literal}_day').val('');
$( "#"+'ezcoa-{/literal}{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}{literal}_month').val('');
$( "#"+'ezcoa-{/literal}{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}{literal}_year').val('');

	
            return false;
        });
	});
})(jQuery);
</script>
{/literal}
<div class="block">
<div class="date">
	<input type="text" name="{$attribute_base}_date_{$attribute.id}" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_date" class=".datepicker" value="{section show=$attribute.content.is_valid}{$attribute.content.timestamp|datetime( 'custom', '%d/%m/%Y')}{/section}" /> <a href="#" id="delete{$attribute.contentclassattribute_id}">Eliminar</a>
	<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_day" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="hidden" name="{$attribute_base}_date_day_{$attribute.id}" value="{section show=$attribute.content.is_valid}{$attribute.content.day}{/section}" />
	<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_month" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="hidden" name="{$attribute_base}_date_month_{$attribute.id}" value="{section show=$attribute.content.is_valid}{$attribute.content.month}{/section}" />
	<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_year" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="hidden" name="{$attribute_base}_date_year_{$attribute.id}" value="{section show=$attribute.content.is_valid}{$attribute.content.year}{/section}" />
</div>
</div>
{/default}
