<?php /*
[ODFImport]
DefaultImportClass=curso_distancia
RegisteredClassArray[]=econferencia
RegisteredClassArray[]=curso_distancia

[econferencia]
DefaultImportTitleAttribute=nombre
DefaultImportBodyAttribute=contenidos
Attribute[nombre]=nombre
Attribute[contenidos]=contenidos
Attribute[fecha_inicio]=fecha_inicio
Attribute[fecha_fin]=fecha_fin
Attribute[antetitulo]=antetitulo
Attribute[subtitulo]=subtitulo
Attribute[entradilla]=entradilla
Attribute[fecha_inicio_oferta]=fecha_inicio_oferta
Attribute[fecha_fin_oferta]=fecha_fin_oferta
Attribute[objetivos]=objetivos
Attribute[consideraciones]=consideraciones

[curso_distancia]
DefaultImportTitleAttribute=nombre
DefaultImportBodyAttribute=programa
Attribute[nombre]=nombre
#Attribute[contenidos]=contenidos
#Attribute[fecha_inicio]=fecha_inicio
#Attribute[fecha_fin]=fecha_fin
Attribute[antetitulo]=antetitulo
Attribute[subtitulo]=subtitulo
Attribute[entradilla]=entradilla
Attribute[fecha_inicio_oferta]=fecha_inicio_oferta
Attribute[fecha_fin_oferta]=fecha_fin_oferta
Attribute[objetivos]=objetivos
#Attribute[consideraciones]=consideraciones
Attribute[duracion]=duracion
Attribute[programa]=programa
Attribute[metodologia]=metodologia
Attribute[materiales]=materiales
Attribute[informacion_complementaria]=informacion_complementaria
Attribute[tutorias]=tutorias
Attribute[evaluacion]=evaluacion
/*?>
