{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<form method="post" action={"basket/encuesta"|ezurl}>

{* DESIGN: Header START *}<div class="box-header">
<h1 class="context-title">Encuesta para la tienda</h1>

{* DESIGN: Mainline *}<div class="header-mainline"></div>

{* DESIGN: Header END *}</div>

{* DESIGN: Content START *}<div class="box-content">
<div class="context-attributes">

<div class="object">


<p>Por favor, escoge la encuesta que se presentará al usuario una vez termine la compra</p>

<br />
<div class="block">
    <label>Encuesta:&nbsp;
    <select name="encuesta">
       <option value="0">Ninguna</option>
       {foreach fetch( 'content', 'list', hash( 'parent_node_id', 12542,
                                                 'sort_by', array( 'published', false() ) )) as $index => $encuesta}
            <option value="{$encuesta.object.id}" {if eq($encuesta.object.id, $encuesta_id )}selected="selected"{/if}>{$encuesta.name}</option>
       {/foreach}
    </select></label>
   
</div>
</div>

</div>
{* DESIGN: Content END *}</div>

<div class="controlbar">
{* DESIGN: Control bar START *}
<div class="block">
    <input class="button" type="submit" name="Send" value="{'Select'|i18n('design/admin/settings')}" />
</div>
{* DESIGN: Control bar END *}
</div>

</form>

